# version: '3.8'

services:
  # nuxt3
  nuxt3:
    image: xcy960815/data-middle-station:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-middle-station-container
    ports:
      - '12583:12583'
    volumes:
      - ./logs:/data-middle-station-container/logs
    environment:
      - NODE_ENV=pre
      - CONFIG_DB_HOST=host.docker.internal
      - CONFIG_DB_PORT=3310
      - CONFIG_DB_USER=root
      - CONFIG_DB_PASSWORD=root
      - CONFIG_DB_NAME=data_middle_station
      - CONFIG_DB_TIMEZONE=+08:00
      - CONFIG_DB_DATE_STRINGS=true
      - KANBAN_DB_NAME=kanban_data
      - KANBAN_DB_HOST=host.docker.internal
      - KANBAN_DB_PORT=3310
      - KANBAN_DB_USER=root
      - KANBAN_DB_PASSWORD=root
      - KANBAN_DB_TIMEZONE=+08:00
      - KANBAN_DB_DATE_STRINGS=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - data-middle-station-network

  # mysql配置
  mysql:
    image: mysql:8.4.2
    container_name: data-middle-station-mysql-container
    command: [
      "--bind-address=0.0.0.0"
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data_middle_station
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - data-middle-station-network

networks:
  data-middle-station-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local



# docker-compose down && docker-compose up --build -d
# docker-compose.yml up -d 